# Generated by Django 4.1.3 on 2022-11-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='artist',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audio',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
